version: "3.8"

services:
  # NestJS backend
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
      target: ${ENV_TYPE}
    ports:
      - ${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}
    volumes:
      - ../backend:/app
    env_file:
      - ./.env
    networks:
      - backend_network
    depends_on:
      - database

  # NextJS frontend
  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
      target: ${ENV_TYPE}
    ports:
      - ${FRONTED_EXTERNAL_PORT}:${FRONTED_INTERNAL_PORT}
    volumes:
      - ../frontend:/app
      - /app/.next
    env_file:
      - ./.env
    networks:
      - backend_network
    depends_on:
      - backend

  # PostgreSQL Database
  database:
    image: postgres
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    env_file:
      - ./.env
    networks:
      - backend_network
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge

volumes:
  postgres:
