# Base stage
FROM node:lts AS base
WORKDIR /app

COPY package.json .
COPY pnpm-lock.yaml .

RUN npm install -g pnpm

# Development stage
FROM base AS dev

WORKDIR /app
RUN pnpm install

COPY . .

CMD ["pnpm", "run", "start:dev"]

# Production stage
FROM base AS prod

WORKDIR /app

RUN pnpm install --production

COPY . .

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs
USER nestjs

CMD ["pnpm", "run", "start:prod"]
